require 'spec_helper'

describe 'bin/bitmap_editor' do
  context 'mystery image' do
    let(:expected_output) do
      <<~OUTPUT
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        OOOOOOOOBBBBBBBBBBOOOBBBBBBBBBOOOBBBBBBBBBBBBBBBOOOBBBBOOOBBBBOOBBBBBBBBBOOBBBBBOOOBBBBOOOOBBBBOOOOO
        OOOOOOOBBBBBBBBBBBBBBBBBBBBBBBBOOBBBBBBBBBBOBBBBOOBBBBBBOOBBBBBBBBBBBBBBBBBBBBBBOOBBBBBOOBBBBBBOOOOO
        OOOOOOBBBBBOOOOBBOBBBBBBOOOOBBBBOBBBBBBOOOOOBBBBBBBBBBBBBBBBBBBBBBOOOOOBBBBBBBBBBOBBBBBBBBBBBOOOOOOO
        OOOOOBBBBBOOOOOOOOBBBBBOOOOOBBBBBBBBBOOOOOOOOBBBBBBBBBBBBBBBBBBBBBOOOOOOBBBBBBBBBBBBBBBBBBBBBOOOOOOO
        OOOOOOBBBBBOOOOBOOBBBBBBOOOBBBBBBBBBBOOOOOOOOBBBBBBBBBBBBBBBBOBBBBBOOOOBBBBBOBBBBBBBBBBBBBBBOOOOOOOO
        OOOOOOOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOOOOOOOOOBBBBBBOOBBBBBOOOOBBBBBBBBBBBBBOOBBBBBBOBBBBBBBOOOOOOOO
        OOOOOOOOBBBBBBBBBBOOBBBBBBBBBBBBOBBBBOOOOOOOOOOBBBBBOOBBBBOOOOOOBBBBBBBBBOOOOOOBBBBOOOBBBBOOOOOOOOOO
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
      OUTPUT
    end
    it 'executes successfully and displays output' do
      expect { system('bin/bitmap_editor examples/mystery_image.txt') }
        .to output(expected_output).to_stdout_from_any_process
    end
  end

  context 'online example' do
    let(:expected_output) do
      <<~OUTPUT
        OOOOO
        OOZZZ
        AWOOO
        OWOOO
        OWOOO
        OWOOO
      OUTPUT
    end
    it 'executes successfully and displays output' do
      expect { system('bin/bitmap_editor examples/online_example.txt') }
        .to output(expected_output).to_stdout_from_any_process
    end

  end
end
